#!/usr/bin/env bash
#
# Interactive setup - collect machine-specific configuration
# Phase: 00 - Must run before all other phases
# Writes: ~/.env.local
#
# shellcheck source=../utils/utils.sh
source "$(dirname "$0")/../utils/utils.sh"

print_header "Interactive Machine Setup"

# ─── Machine type ─────────────────────────────────────────────────────────────

detect_default_type() {
    if compgen -G "/sys/class/power_supply/BAT*" > /dev/null 2>&1; then
        echo "laptop"
    else
        echo "desktop"
    fi
}

prompt_machine_type() {
    local default
    default="$(detect_default_type)"

    log_section "Machine Type"
    log_info "Detected default: $default"
    read -r -p "Machine type (laptop/desktop) [$default]: " input
    MACHINE_TYPE="${input:-$default}"
    MACHINE_TYPE="${MACHINE_TYPE,,}"

    if [[ "$MACHINE_TYPE" != "laptop" && "$MACHINE_TYPE" != "desktop" ]]; then
        log_error "Invalid machine type: $MACHINE_TYPE"
        exit 1
    fi

    log_success "Machine type: $MACHINE_TYPE"
}

# ─── Monitor detection ────────────────────────────────────────────────────────

auto_detect_monitors() {
    command_exists hyprctl && command_exists jq || return 1

    local monitors_json
    monitors_json="$(hyprctl monitors -j 2>/dev/null)" || return 1
    [[ "$(jq 'length' <<< "$monitors_json")" -eq 0 ]] && return 1

    log_info "Detected monitors (sorted left → right):"
    jq -r 'sort_by(.x) | .[] | "    \(.name)  \(.width)x\(.height)  @ x=\(.x)"' <<< "$monitors_json"
    echo ""

    MONITOR_PRIMARY="$(jq -r 'sort_by(.x) | .[0].name' <<< "$monitors_json")"
    MONITOR_SECONDARY="$(jq -r 'sort_by(.x) | .[1].name // ""' <<< "$monitors_json")"
}

prompt_monitors() {
    log_section "Monitor Configuration"
    MONITOR_PRIMARY=""
    MONITOR_SECONDARY=""

    if [[ "$MACHINE_TYPE" == "laptop" ]]; then
        MONITOR_PRIMARY="eDP-1"
        MONITOR_SECONDARY=""
        log_info "Laptop: primary set to $MONITOR_PRIMARY, no secondary"
        return
    fi

    if auto_detect_monitors; then
        log_info "Auto-detected — primary: $MONITOR_PRIMARY, secondary: ${MONITOR_SECONDARY:-none}"
    else
        log_warning "Could not auto-detect monitors (hyprctl/jq unavailable or not running)"
    fi

    read -r -p "Primary monitor name [$MONITOR_PRIMARY]: " input
    MONITOR_PRIMARY="${input:-$MONITOR_PRIMARY}"

    if [[ -z "$MONITOR_PRIMARY" ]]; then
        log_error "Primary monitor is required for desktop"
        exit 1
    fi

    read -r -p "Secondary monitor name (leave blank for none) [$MONITOR_SECONDARY]: " input
    MONITOR_SECONDARY="${input:-$MONITOR_SECONDARY}"

    log_success "Primary: $MONITOR_PRIMARY"
    [[ -n "$MONITOR_SECONDARY" ]] && log_success "Secondary: $MONITOR_SECONDARY"
}

# ─── Git configuration ────────────────────────────────────────────────────────

prompt_git_config() {
    log_section "Git Configuration"

    read -r -p "Git personal name: "  GIT_USER_NAME
    read -r -p "Git personal email: " GIT_USER_EMAIL
    read -r -p "Git work name (leave blank to skip): "  GIT_WORK_NAME
    read -r -p "Git work email (leave blank to skip): " GIT_WORK_EMAIL
    read -r -p "Company name (leave blank to skip): " COMPANY_NAME
}

# ─── Write ~/.env.local ───────────────────────────────────────────────────────

write_env_local() {
    cat > "$ENV_LOCAL" <<ENV
# Machine configuration — generated by 00-setup.sh
# Edit manually or re-run ./runs/00-setup.sh to regenerate

export MACHINE_TYPE=$MACHINE_TYPE
export MONITOR_PRIMARY=$MONITOR_PRIMARY
export MONITOR_SECONDARY=$MONITOR_SECONDARY

# Git
export GIT_USER_NAME="$GIT_USER_NAME"
export GIT_USER_EMAIL="$GIT_USER_EMAIL"
export GIT_WORK_NAME="$GIT_WORK_NAME"
export GIT_WORK_EMAIL="$GIT_WORK_EMAIL"
export COMPANY_NAME="$COMPANY_NAME"
ENV

    log_success "Written to $ENV_LOCAL"
    echo ""
    cat "$ENV_LOCAL"
}

# ─── Run ──────────────────────────────────────────────────────────────────────

prompt_machine_type
prompt_monitors
prompt_git_config

log_section "Summary"
echo "  Machine type  : $MACHINE_TYPE"
echo "  Primary mon.  : $MONITOR_PRIMARY"
echo "  Secondary mon.: ${MONITOR_SECONDARY:-none}"
echo "  Git name      : $GIT_USER_NAME"
echo "  Git email     : $GIT_USER_EMAIL"
[[ -n "$GIT_WORK_NAME" ]] && echo "  Work name     : $GIT_WORK_NAME"
[[ -n "$GIT_WORK_EMAIL" ]] && echo "  Work email    : $GIT_WORK_EMAIL"
echo ""

read -r -p "Save this configuration? (Y/n): " confirm
if [[ "${confirm,,}" == "n" ]]; then
    log_warning "Aborted — nothing written"
    exit 1
fi

write_env_local

print_footer "Setup complete — continuing install..."
