#!/usr/bin/env bash
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ENV_LOCAL="$HOME/.env.local"

usage() {
    cat <<'EOF'
Usage: ./machine-conf.sh [options]
Regenerate ~/.env.local with machine-specific config.
Options:
  --type <laptop|desktop>    Set the machine type without prompting
  --primary <name>           Set the primary monitor name (desktop only)
  --secondary <name>         Set the secondary monitor name (desktop only)
  --non-interactive          Fail if required values are missing instead of prompting
  -h, --help                 Show this help message
EOF
}

DEFAULT_TYPE="desktop"
compgen -G "/sys/class/power_supply/BAT*" > /dev/null 2>&1 && DEFAULT_TYPE="laptop"

MACHINE_TYPE=""
MONITOR_PRIMARY=""
MONITOR_SECONDARY=""
NON_INTERACTIVE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --type)            MACHINE_TYPE="$2";      shift 2 ;;
        --primary)         MONITOR_PRIMARY="$2";   shift 2 ;;
        --secondary)       MONITOR_SECONDARY="$2"; shift 2 ;;
        --non-interactive) NON_INTERACTIVE=1;       shift   ;;
        -h|--help)         usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    esac
done

prompt_value() {
    local __var_ref="$1" __prompt="$2" __default="$3"
    [[ ${!__var_ref} != "" ]] && return
    if [[ $NON_INTERACTIVE -eq 1 ]]; then
        echo "Missing required value: $__prompt" >&2; exit 1
    fi
    read -r -p "$__prompt [$__default]: " __input
    printf -v "$__var_ref" '%s' "${__input:-$__default}"
}

prompt_machine_type() {
    prompt_value MACHINE_TYPE "Is this a laptop or desktop?" "$DEFAULT_TYPE"
    MACHINE_TYPE="${MACHINE_TYPE,,}"
    if [[ "$MACHINE_TYPE" != "laptop" && "$MACHINE_TYPE" != "desktop" ]]; then
        echo "Invalid machine type: $MACHINE_TYPE" >&2; exit 1
    fi
}

auto_detect_monitors() {
    command -v hyprctl &>/dev/null && command -v jq &>/dev/null || return 1
    local monitors_json
    monitors_json="$(hyprctl monitors -j 2>/dev/null)" || return 1
    [[ "$(jq 'length' <<< "$monitors_json")" -eq 0 ]] && return 1

    echo "Auto-detected monitors (sorted left → right):"
    jq -r 'sort_by(.x) | .[] | "  \(.name)  \(.width)x\(.height)  @ x=\(.x)"' <<< "$monitors_json"
    echo ""

    [[ -z "$MONITOR_PRIMARY" ]] && \
        MONITOR_PRIMARY="$(jq -r 'sort_by(.x) | .[0].name' <<< "$monitors_json")"
    [[ -z "$MONITOR_SECONDARY" ]] && \
        MONITOR_SECONDARY="$(jq -r 'sort_by(.x) | .[1].name // ""' <<< "$monitors_json")"
}

prompt_monitors_if_needed() {
    if [[ "$MACHINE_TYPE" == "desktop" ]]; then
        if auto_detect_monitors && [[ $NON_INTERACTIVE -eq 0 ]]; then
            read -r -p "Primary monitor [$MONITOR_PRIMARY]: " input
            MONITOR_PRIMARY="${input:-$MONITOR_PRIMARY}"
            read -r -p "Secondary monitor (blank = none) [$MONITOR_SECONDARY]: " input
            MONITOR_SECONDARY="${input:-$MONITOR_SECONDARY}"
        else
            prompt_value MONITOR_PRIMARY "Enter primary monitor name (e.g., DP-3)" ""
            if [[ $NON_INTERACTIVE -eq 1 && -z "$MONITOR_PRIMARY" ]]; then
                echo "Primary monitor is required for desktop in non-interactive mode" >&2; exit 1
            fi
            [[ $NON_INTERACTIVE -eq 0 ]] && \
                read -r -p "Enter secondary monitor name (leave blank for single display): " MONITOR_SECONDARY
        fi
    else
        MONITOR_PRIMARY="${MONITOR_PRIMARY:-eDP-1}"
        MONITOR_SECONDARY=""
    fi
}

prompt_machine_type
prompt_monitors_if_needed

# Preserve existing git vars if .env.local already exists
GIT_USER_NAME="" GIT_USER_EMAIL="" GIT_WORK_NAME="" GIT_WORK_EMAIL=""
if [[ -f "$ENV_LOCAL" ]]; then
    # shellcheck source=/dev/null
    source "$ENV_LOCAL"
fi

cat > "$ENV_LOCAL" <<CONFIG
# Machine configuration — generated by machine-conf.sh
# Edit manually or re-run ./machine-conf.sh to regenerate

export MACHINE_TYPE=$MACHINE_TYPE
export MONITOR_PRIMARY=$MONITOR_PRIMARY
export MONITOR_SECONDARY=$MONITOR_SECONDARY

# Git
export GIT_USER_NAME="$GIT_USER_NAME"
export GIT_USER_EMAIL="$GIT_USER_EMAIL"
export GIT_WORK_NAME="$GIT_WORK_NAME"
export GIT_WORK_EMAIL="$GIT_WORK_EMAIL"
CONFIG

echo ""
echo "Configuration saved to $ENV_LOCAL:"
cat "$ENV_LOCAL"
